version: '3.0'
services:
  app:
    container_name: wallet
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:latest
    environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_HOST: ${MYSQL_HOST}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3307:3307
