apiVersion: v1
kind: Service
metadata:
  name: wallet-ts-service 
spec:
  selector:
    app: server
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 5000
    nodePort: 31110

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
